### ISSUE TITLE
glossary does not generate output as shown in Readme.md

### ISSUE THREAD

**Issue by DrVanScott** [erichs/composure#17]
Hi,

glossary does not show the built in commands. Are those excluded meanwhile? So please update your example.

**Comment by DrVanScott** [comment]
this is due to 9089fe3 resp. #14

**Comment by erichs** [comment]
Good catch! This was unintended... Fix is forthcoming!

**Comment by erichs** [comment]
Reopening due to [comment](https://github.com/erichs/composure/commit/5c3698df33cf92f9dbe75b807b1d29729989baaa#commitcomment-16809325) by @DrVanScott.

I see a couple of options here, one might be to add a `-e` (think ENV) flag for the `glossary` command, much like the `revise` command: this would pull functions from the running env (slower, but possibly more complete or accurate for your use case).

Another option might be to allow for configuration, such that multiple "source" directories could be specified. If you happen to use the composure metadata system outside of the composure git directory, but still want `glossary` to support functions in arbitrary directories, that could be useful.

Would either of those options help? Do you see other options I might be missing?

**Comment by DrVanScott** [comment]
@erichs 

Please have look at https://github.com/erichs/composure/compare/master...DrVanScott:master
